import React, { useState } from 'react';
import { Sparkles, RefreshCw, Cpu } from 'lucide-react';
import { Modal } from '../../ui/Modal';
import { Button } from '../../ui/Button';
import { timeAgo } from '../../../utils/timeAgo';
import type { WorkflowSpec } from '../../../types/spec.types';

interface Props {
  spec: WorkflowSpec;
  projectName: string;
  regenerating?: boolean;
  onRegenerate: () => void;
}

/** The blueprint hero, with honest provenance and a guarded Regenerate. (FE5.2) */
export const SpecHeader: React.FC<Props> = ({ spec, projectName, regenerating, onRegenerate }) => {
  const [confirming, setConfirming] = useState(false);

  const engine = spec.provider === 'gemini' ? 'Gemini AI' : 'the built-in template engine';
  const when = timeAgo(spec.generatedAt);

  return (
    <>
      <div className="bg-teal-50 rounded-2xl p-8 border border-teal-100 flex items-start gap-5">
        <div className="bg-white rounded-xl p-3 shadow-sm shrink-0">
          <Sparkles className="text-teal-500" size={24} />
        </div>
        <div className="flex-1 min-w-0">
          <h1 className="font-poppins text-3xl lg:text-[36px] font-bold text-[#0F766E] leading-tight mb-2">
            The blueprint for <span className="text-slate-900">{projectName || 'your project'}</span> is ready
          </h1>
          <p className="text-teal-900/70 text-lg max-w-3xl">
            Everything below is written in plain language. Review each section, edit anything that isn't
            right, then confirm the checklist and approve.
          </p>
          <p className="mt-4 flex items-center gap-2 text-xs font-semibold text-teal-800/70">
            <Cpu size={13} />
            Generated by {engine} · v{spec.version}{when && ` · ${when}`}
          </p>
        </div>
        <Button
          onClick={() => setConfirming(true)}
          isLoading={regenerating}
          aria-label="Regenerate the blueprint from your intake"
          className="shrink-0 bg-white text-[#0F766E] border border-teal-200 hover:bg-teal-50 font-bold flex items-center gap-2"
        >
          <RefreshCw size={16} /> Regenerate
        </Button>
      </div>

      <Modal isOpen={confirming} onClose={() => setConfirming(false)} title="Regenerate this blueprint?">
        <div className="p-6 pt-0 space-y-4">
          <p className="text-sm text-slate-600 leading-relaxed">
            Regenerating rebuilds the blueprint from your intake answers. <strong>Your edits, checklist
            ticks and reviewed risks will be cleared</strong> and a new version will be created.
          </p>
          <div className="flex justify-end gap-3">
            <Button onClick={() => setConfirming(false)} className="bg-slate-100 text-slate-700 hover:bg-slate-200">
              Keep this version
            </Button>
            <Button
              onClick={() => { setConfirming(false); onRegenerate(); }}
              className="bg-[#0F766E] hover:bg-[#0D6B63] text-white font-bold"
            >
              Regenerate
            </Button>
          </div>
        </div>
      </Modal>
    </>
  );
};
