import React, { useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { Logo } from '../../components/shared/Logo';
import { Avatar } from '../../components/ui/Avatar';
import { cn } from '../../utils/classNames';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Bell, HelpCircle, Terminal, Package, Book, LifeBuoy,
  Download, Copy, X, FileText, Folder, FolderOpen, ChevronRight,
  FileCode2, FileJson, Database
} from 'lucide-react';

// ---------- File Tree Types ----------
type TreeNodeType = 'folder' | 'file';
interface TreeNode {
  name: string;
  type: TreeNodeType;
  children?: TreeNode[];
  lang?: string;
  count?: string;
  content?: string;
}

// ---------- Mock File Tree ----------
const FILE_TREE: TreeNode[] = [
  {
    name: 'my-org-clinic', type: 'folder', children: [
      {
        name: 'frontend', type: 'folder', children: [
          {
            name: 'src', type: 'folder', children: [
              { name: 'components', type: 'folder', count: '47 files' },
              { name: 'pages', type: 'folder', count: '18 files' },
              { name: 'services', type: 'folder', count: '8 files' },
              { name: 'store', type: 'folder', count: '3 files' },
            ]
          },
          { name: 'package.json', type: 'file', lang: 'json', content: `{\n  "name": "my-org-clinic-frontend",\n  "version": "1.0.0",\n  "dependencies": {\n    "react": "^19.1.0",\n    "tailwindcss": "^4.1.0",\n    "react-router-dom": "^7.0.0",\n    "zustand": "^5.0.0"\n  }\n}` },
          { name: 'tailwind.config.ts', type: 'file', lang: 'ts', content: `import type { Config } from 'tailwindcss';\n\nexport default {\n  content: ['./src/**/*.{ts,tsx}'],\n  theme: {\n    extend: {\n      colors: {\n        brand: '#0F766E',\n      },\n    },\n  },\n} satisfies Config;` },
          { name: 'vite.config.ts', type: 'file', lang: 'ts', content: `import { defineConfig } from 'vite';\nimport react from '@vitejs/plugin-react';\n\nexport default defineConfig({\n  plugins: [react()],\n  server: { port: 3000 },\n});` },
        ]
      },
      {
        name: 'backend', type: 'folder', children: [
          {
            name: 'src', type: 'folder', children: [
              { name: 'controllers', type: 'folder', count: '4 files' },
              { name: 'routes', type: 'folder', count: '4 files' },
              { name: 'models', type: 'folder', count: '4 files' },
              { name: 'middleware', type: 'folder', count: '3 files' },
              { name: 'services', type: 'folder', count: '4 files' },
            ]
          },
          { name: 'migrations', type: 'folder', count: '4 files' },
          { name: 'package.json', type: 'file', lang: 'json', content: `{\n  "name": "my-org-clinic-backend",\n  "version": "1.0.0",\n  "dependencies": {\n    "express": "^4.18.2",\n    "sequelize": "^6.35.0",\n    "pg": "^8.11.0",\n    "jsonwebtoken": "^9.0.0",\n    "bcrypt": "^5.1.1"\n  }\n}` },
          { name: '.env.example', type: 'file', lang: 'text', content: `DATABASE_URL=postgresql://user:password@localhost:5432/alshifa\nJWT_SECRET=your-256-bit-secret-here\nPORT=4000\nSENDGRID_API_KEY=\nSENTRY_DSN=` },
        ]
      },
      {
        name: 'database', type: 'folder', children: [
          { name: 'schema.sql', type: 'file', lang: 'sql', content: `-- My Organization Schema\n-- Generated by FlowForge v2.4.1\n\nCREATE TABLE patients (\n  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),\n  full_name VARCHAR(255) NOT NULL,\n  phone VARCHAR(20),\n  age INTEGER,\n  medical_history TEXT,\n  created_at TIMESTAMPTZ DEFAULT NOW()\n);\n\nCREATE TABLE appointments (\n  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),\n  patient_id UUID REFERENCES patients(id),\n  doctor_id UUID,\n  date DATE NOT NULL,\n  time TIME NOT NULL,\n  status VARCHAR(50) DEFAULT 'SCHEDULED'\n);` },
          { name: 'seed.sql', type: 'file', lang: 'sql', content: `-- Seed Data\nINSERT INTO patients (full_name, phone, age)\nVALUES\n  ('User Name', '+92300-1234567', 35),\n  ('Fatima Malik', '+92311-9876543', 28);` },
        ]
      },
      { name: 'docker-compose.yml', type: 'file', lang: 'yaml', content: `version: '3.9'\nservices:\n  postgres:\n    image: postgres:16.5\n    environment:\n      POSTGRES_DB: alshifa\n      POSTGRES_USER: admin\n      POSTGRES_PASSWORD: secret\n    ports:\n      - "5432:5432"\n  backend:\n    build: ./backend\n    ports:\n      - "4000:4000"\n    depends_on: [postgres]\n  frontend:\n    build: ./frontend\n    ports:\n      - "3000:3000"` },
      { name: 'README.md', type: 'file', lang: 'md', content: `# My Organization — Generated by FlowForge\n\n## Quick Start\n\n\`\`\`bash\ndocker-compose up -d\ncd frontend && npm install && npm run dev\ncd backend && npm install && npm run dev\n\`\`\`\n\n## Stack\n- **Frontend**: React 19 + Tailwind CSS 4 + Vite\n- **Backend**: Node.js 22 + Express + Sequelize ORM\n- **Database**: PostgreSQL 16.5\n\n> Licensed under MIT. Generated in 8m 12s.` },
    ]
  }
];

// ---------- File Icon helper ----------
const FileIcon: React.FC<{ node: TreeNode; isOpen?: boolean }> = ({ node, isOpen }) => {
  if (node.type === 'folder') {
    return isOpen ? <FolderOpen size={14} className="text-amber-400 shrink-0" /> : <Folder size={14} className="text-amber-400 shrink-0" />;
  }
  if (node.lang === 'json') return <FileJson size={14} className="text-amber-500 shrink-0" />;
  if (node.lang === 'sql') return <Database size={14} className="text-blue-400 shrink-0" />;
  if (node.lang === 'ts' || node.lang === 'tsx') return <FileCode2 size={14} className="text-blue-500 shrink-0" />;
  return <FileText size={14} className="text-slate-400 shrink-0" />;
};

// ---------- Tree Node Component ----------
const TreeNodeComponent: React.FC<{
  node: TreeNode;
  depth?: number;
  onSelectFile: (node: TreeNode) => void;
  selectedFile: TreeNode | null;
}> = ({ node, depth = 0, onSelectFile, selectedFile }) => {
  const [open, setOpen] = useState(depth < 2);

  if (node.type === 'folder') {
    return (
      <div>
        <button
          onClick={() => setOpen(p => !p)}
          className="flex items-center gap-1.5 w-full text-left py-1 px-2 hover:bg-slate-50 rounded-md transition-colors group"
          style={{ paddingLeft: `${8 + depth * 16}px` }}
        >
          <ChevronRight size={12} className={cn('text-slate-400 transition-transform shrink-0', open && 'rotate-90')} />
          <FileIcon node={node} isOpen={open} />
          <span className="text-xs font-semibold text-slate-700">{node.name}</span>
          {node.count && <span className="text-[10px] text-slate-400 ml-auto">{node.count}</span>}
        </button>
        <AnimatePresence>
          {open && node.children && (
            <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }} transition={{ duration: 0.15 }} className="overflow-hidden">
              {node.children.map((child, i) => (
                <TreeNodeComponent key={i} node={child} depth={depth + 1} onSelectFile={onSelectFile} selectedFile={selectedFile} />
              ))}
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    );
  }

  return (
    <button
      onClick={() => onSelectFile(node)}
      className={cn(
        'flex items-center gap-1.5 w-full text-left py-1 px-2 rounded-md transition-colors text-xs',
        selectedFile?.name === node.name ? 'bg-teal-50 text-[#0F766E] font-semibold' : 'text-slate-600 hover:bg-slate-50'
      )}
      style={{ paddingLeft: `${8 + depth * 16}px` }}
    >
      <FileIcon node={node} />
      {node.name}
    </button>
  );
};

// ---------- Syntax color helper for preview ----------
const langColors: Record<string, string> = { json: 'text-amber-300', sql: 'text-blue-300', ts: 'text-sky-300', yaml: 'text-green-300', md: 'text-slate-300', text: 'text-slate-300' };

const GenerationArtifactsPage: React.FC = () => {
  const navigate = useNavigate();
  const { projectId } = useParams();
  const [selectedFile, setSelectedFile] = useState<TreeNode | null>(null);
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    if (selectedFile?.content) {
      navigator.clipboard.writeText(selectedFile.content);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  return (
    <div className="min-h-screen bg-[#F8FAFC] flex flex-col">
      {/* Navbar */}
      <nav className="h-14 bg-[#134E4A] flex items-center justify-between px-6 shrink-0 z-50">
        <div className="flex items-center space-x-6">
          <Logo size="sm" variant="light" useSecondary={true} />
          <div className="h-4 w-[1px] bg-white/20" />
          <div className="flex items-center space-x-2 text-xs font-medium">
            <span className="text-white/50">My Organization</span>
            <span className="text-white/30">›</span>
            <span className="text-white">Artifacts</span>
          </div>
        </div>
        <div className="hidden md:flex items-center space-x-8">
          <button className="text-sm font-bold text-white/40 hover:text-white/70 transition-colors pb-1 mt-1 border-b-2 border-transparent"
            onClick={() => navigate(`/project/${projectId || 'new'}/alerts`)}>Workflows</button>
          <button className="text-sm font-bold text-white/40 hover:text-white/70 transition-colors pb-1 mt-1 border-b-2 border-transparent">Dashboard</button>
        </div>
        <div className="flex items-center space-x-4">
          <button className="text-white/70 hover:text-white"><Bell size={20} /></button>
          <button className="text-white/70 hover:text-white"><HelpCircle size={20} /></button>
          <Avatar name="Maryam Farooq" size="sm" className="bg-[#34D399] text-[#134E4A]" />
        </div>
      </nav>

      <div className="flex-1 flex overflow-hidden">
        {/* Left Sidebar */}
        <aside className="w-48 bg-white border-r border-slate-200 shrink-0 flex flex-col justify-between p-4">
          <div className="space-y-1">
            <button
              className="w-full flex items-center space-x-3 px-3 py-2 text-slate-500 hover:bg-slate-50 rounded-lg text-sm font-medium transition-colors"
              onClick={() => navigate(`/project/${projectId || 'new'}/logs`)}
            >
              <Terminal size={16} /><span>Logs</span>
            </button>
            <button className="w-full flex items-center space-x-3 px-3 py-2 bg-teal-50 text-[#0F766E] font-bold rounded-lg text-sm border-l-2 border-[#0F766E]">
              <Package size={16} /><span>Artifacts</span>
            </button>
          </div>
          <div className="space-y-1 border-t border-slate-100 pt-4">
            <button className="w-full flex items-center space-x-3 px-3 py-2 text-slate-400 hover:text-slate-600 rounded-lg text-sm transition-colors">
              <Book size={14} /><span>Docs</span>
            </button>
            <button className="w-full flex items-center space-x-3 px-3 py-2 text-slate-400 hover:text-slate-600 rounded-lg text-sm transition-colors">
              <LifeBuoy size={14} /><span>Support</span>
            </button>
          </div>
        </aside>

        {/* Main */}
        <main className="flex-1 overflow-y-auto p-8">
          <div className="max-w-6xl mx-auto">
            {/* Header */}
            <div className="flex items-start justify-between mb-6">
              <div>
                <h1 className="text-2xl font-bold text-slate-900 font-poppins">Build Artifacts — My Organization</h1>
                <p className="text-sm text-slate-500 mt-1">Generated May 8, 2026 at 11:42 AM</p>
              </div>
              <button className="flex items-center gap-2 h-10 px-5 bg-[#0F766E] hover:bg-[#0D6B63] text-white rounded-xl text-sm font-bold transition-colors shadow-sm">
                <Download size={15} />Download All (ZIP)
              </button>
            </div>

            <div className="flex gap-5">
              {/* File Tree */}
              <div className={cn('bg-white border border-slate-200 rounded-2xl shadow-sm p-4 overflow-y-auto transition-all', selectedFile ? 'w-2/5' : 'w-full')}>
                <p className="text-[10px] font-bold uppercase tracking-widest text-slate-400 mb-3 px-2">Project Files</p>
                {FILE_TREE.map((node, i) => (
                  <TreeNodeComponent key={i} node={node} depth={0} onSelectFile={setSelectedFile} selectedFile={selectedFile} />
                ))}
              </div>

              {/* File Preview Panel */}
              <AnimatePresence>
                {selectedFile && (
                  <motion.div
                    initial={{ opacity: 0, x: 20 }}
                    animate={{ opacity: 1, x: 0 }}
                    exit={{ opacity: 0, x: 20 }}
                    transition={{ duration: 0.2 }}
                    className="flex-1 bg-[#0F172A] rounded-xl overflow-hidden flex flex-col"
                  >
                    {/* Panel header */}
                    <div className="flex items-center justify-between px-4 py-3 bg-[#0A1020] border-b border-slate-800">
                      <div className="flex items-center gap-2">
                        <FileIcon node={selectedFile} />
                        <span className="text-xs font-semibold text-slate-300">{selectedFile.name}</span>
                        <span className="text-[10px] text-slate-600 bg-slate-800 px-1.5 py-0.5 rounded font-mono">{selectedFile.lang}</span>
                      </div>
                      <div className="flex items-center gap-2">
                        <button onClick={handleCopy} className="flex items-center gap-1.5 text-xs text-slate-400 hover:text-white transition-colors">
                          <Copy size={12} />{copied ? 'Copied!' : 'Copy'}
                        </button>
                        <button onClick={() => setSelectedFile(null)} className="text-slate-500 hover:text-white transition-colors ml-2">
                          <X size={14} />
                        </button>
                      </div>
                    </div>
                    {/* Code content */}
                    <pre className={cn('p-5 font-mono text-xs overflow-auto flex-1 leading-relaxed', langColors[selectedFile.lang || 'text'])}>
                      {selectedFile.content}
                    </pre>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>

            {/* Artifact Stats Bar */}
            <div className="flex flex-wrap gap-6 mt-6 text-sm text-slate-500">
              <span>📄 <strong className="text-slate-700">127</strong> total files</span>
              <span>📦 <strong className="text-slate-700">12.4 MB</strong> total size</span>
              <span>⚡ <strong className="text-slate-700">8m 12s</strong> generation time</span>
              <span>🔑 <strong className="text-slate-700">MIT</strong> Licensed</span>
            </div>
          </div>
        </main>
      </div>
    </div>
  );
};

export default GenerationArtifactsPage;
