import React, { useEffect, useRef } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { Button } from '../../components/ui/Button';
import { cn } from '../../utils/classNames';
import {
  Sparkles, AlertTriangle, ArrowRight, Loader2, Database, Users, BellRing,
  PlusCircle, Undo2, Info, ShieldCheck,
} from 'lucide-react';
import { useProject } from '../../hooks/useProjects';
import {
  useSpec, useGenerateSpec, useApplySuggestion, useApproveSpec,
  useUpdateSpec, useResolveRisk, useConfirmChecklistItem,
} from '../../hooks/useSpec';
import { EntityCard } from '../../components/features/spec/EntityCard';
import { RolePermissionsTable } from '../../components/features/spec/RolePermissionsTable';
import { BusinessRulesSection } from '../../components/features/spec/BusinessRulesSection';
import { WorkflowGraph } from '../../components/features/spec/WorkflowGraph';
import { SpecHeader } from '../../components/features/spec/SpecHeader';
import { ApprovalChecklist } from '../../components/features/spec/ApprovalChecklist';
import type { ApiError } from '../../types/global.types';

const BlueprintReviewPage: React.FC = () => {
  const navigate = useNavigate();
  const { projectId } = useParams();

  const { data: project } = useProject(projectId);
  const specQuery = useSpec(projectId);
  const generate = useGenerateSpec(projectId);
  const applySuggestion = useApplySuggestion(projectId);
  const approve = useApproveSpec(projectId);
  const updateSpec = useUpdateSpec(projectId);
  const resolveRisk = useResolveRisk(projectId);
  const confirmItem = useConfirmChecklistItem(projectId);

  const spec = specQuery.data;
  const autoGenerated = useRef(false);

  // Auto-generate the blueprint exactly once when none exists (404 = not generated yet).
  useEffect(() => {
    const status = (specQuery.error as ApiError | null)?.response?.status;
    if (specQuery.isError && status === 404 && !autoGenerated.current) {
      autoGenerated.current = true;
      generate.mutate();
    }
    // `generate` is intentionally excluded — the ref makes this a one-shot.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [specQuery.isError, specQuery.error]);

  const handleApprove = () => {
    approve.mutate(undefined, {
      onSuccess: () => navigate(`/project/${projectId}/alerts`),
    });
  };

  // Loading / generating state
  if (!spec) {
    const failed =
      specQuery.isError &&
      (specQuery.error as ApiError | null)?.response?.status !== 404 &&
      !generate.isPending;
    return (
      <div className="min-h-[70vh] flex flex-col items-center justify-center text-center gap-4">
        {failed ? (
          <>
            <AlertTriangle className="w-10 h-10 text-amber-500" />
            <h2 className="text-lg font-bold text-slate-800">Couldn't load the blueprint</h2>
            <Button onClick={() => generate.mutate()} isLoading={generate.isPending} className="bg-[#0F766E] text-white">
              Try again
            </Button>
          </>
        ) : (
          <>
            <Loader2 className="w-10 h-10 animate-spin text-[#0F766E]" />
            <h2 className="text-lg font-bold text-slate-800 font-poppins">Generating your blueprint…</h2>
            <p className="text-sm text-slate-500">Turning your intake into a structured plan.</p>
          </>
        )}
      </div>
    );
  }

  const saving = updateSpec.isPending;
  const allConfirmed = spec.checklist.every((c) => c.userConfirmed);
  const canApprove = spec.validationErrors.length === 0 && allConfirmed;
  const pendingSuggestions = spec.suggestions.filter((s) => !s.applied);
  const openRisks = spec.risks.filter((r) => !r.resolved);
  const generalExplanations = spec.explanations.filter(
    (e) => !spec.entities.some((entity) => entity.label === e.subject)
  );
  const unconfirmedCount = spec.checklist.filter((c) => !c.userConfirmed).length;

  const blockedReason = spec.validationErrors.length > 0
    ? spec.validationErrors[0]
    : !allConfirmed
      ? `Confirm all ${unconfirmedCount} remaining checklist ${unconfirmedCount === 1 ? 'item' : 'items'} to approve.`
      : '';

  return (
    <div className="bg-[#F8FAFC]">
      {/* The rail only sits beside the content once it also gets its narrow width (xl).
          Using lg here left it w-full + shrink-0 between 1024–1279px, overlapping the content. */}
      <main className="max-w-[1400px] mx-auto flex flex-col xl:flex-row gap-8 items-start relative">
        {/* Center content */}
        <div className="flex-1 space-y-12 pb-32 min-w-0">
          <SpecHeader
            spec={spec}
            projectName={project?.name || ''}
            regenerating={generate.isPending}
            onRegenerate={() => generate.mutate()}
          />

          {/* Validation errors — these block approval */}
          {spec.validationErrors.length > 0 && (
            <div className="bg-red-50 border border-red-200 rounded-2xl p-5">
              <h3 className="text-sm font-bold text-red-800 flex items-center gap-2 mb-2">
                <AlertTriangle size={16} /> {spec.validationErrors.length} issue
                {spec.validationErrors.length === 1 ? '' : 's'} must be fixed before approving
              </h3>
              <ul className="list-disc list-inside space-y-1">
                {spec.validationErrors.map((e) => (
                  <li key={e} className="text-xs text-red-700">{e}</li>
                ))}
              </ul>
            </div>
          )}

          {/* Entities — editable */}
          <section>
            <div className="flex items-center justify-between mb-6">
              <h2 className="font-poppins text-2xl font-bold text-slate-900 flex items-center gap-2">
                <Database size={22} className="text-teal-600" /> What Your App Will Track
              </h2>
              <span className="bg-teal-50 text-teal-700 px-3 py-1 rounded-full text-xs font-bold">
                {spec.entities.length} Data Collections
              </span>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {spec.entities.map((entity) => (
                <EntityCard
                  key={entity.key}
                  entity={entity}
                  explanation={spec.explanations.find((e) => e.subject === entity.label)?.text}
                  disabled={saving}
                  onChange={(next) =>
                    updateSpec.mutate({
                      entities: spec.entities.map((e) => (e.key === next.key ? next : e)),
                    })
                  }
                />
              ))}
            </div>
          </section>

          {/* Workflow — states AND transitions */}
          <section className="pt-8 border-t border-slate-200">
            <h2 className="font-poppins text-2xl font-bold text-slate-900 mb-6">How Work Moves Forward</h2>
            <WorkflowGraph states={spec.states} transitions={spec.transitions} roles={spec.roles} />
          </section>

          {/* Roles — editable permissions */}
          <section className="pt-8 border-t border-slate-200">
            <h2 className="font-poppins text-2xl font-bold text-slate-900 mb-6 flex items-center gap-2">
              <Users size={22} className="text-teal-600" /> Who Can Do What
            </h2>
            <div className="space-y-6">
              {spec.roles.map((role) => (
                <RolePermissionsTable
                  key={role.key}
                  role={role}
                  disabled={saving}
                  onChange={(next) =>
                    updateSpec.mutate({
                      roles: spec.roles.map((r) => (r.key === next.key ? next : r)),
                    })
                  }
                />
              ))}
            </div>
          </section>

          {/* Business rules — editable, previously not rendered at all */}
          <BusinessRulesSection
            rules={spec.businessRules}
            disabled={saving}
            onChange={(rules) => updateSpec.mutate({ businessRules: rules })}
          />

          {/* Alerts */}
          <section className="pt-8 border-t border-slate-200">
            <h2 className="font-poppins text-2xl font-bold text-slate-900 mb-6 flex items-center gap-2">
              <BellRing size={22} className="text-teal-600" /> Alerts &amp; Notifications
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              {spec.notificationTriggers.map((n) => (
                <div key={n.event} className="bg-white rounded-xl border border-slate-200 p-4 shadow-sm">
                  <div className="flex items-center justify-between mb-1">
                    <h4 className="font-semibold text-slate-800 text-sm">{n.event}</h4>
                    <span className="text-[9px] font-bold text-teal-700 bg-teal-50 px-2 py-0.5 rounded uppercase">
                      {n.channel}
                    </span>
                  </div>
                  <p className="text-xs text-slate-500">{n.description}</p>
                </div>
              ))}
            </div>
          </section>

          {/* Plain-language explanations that aren't tied to one collection */}
          {generalExplanations.length > 0 && (
            <section className="pt-8 border-t border-slate-200">
              <h2 className="font-poppins text-2xl font-bold text-slate-900 mb-6 flex items-center gap-2">
                <Info size={22} className="text-teal-600" /> In Plain Language
              </h2>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {generalExplanations.map((e) => (
                  <div key={e.subject} className="bg-white rounded-xl border border-slate-200 p-4 shadow-sm">
                    <h4 className="font-semibold text-slate-800 text-sm mb-1">{e.subject}</h4>
                    <p className="text-xs text-slate-500 leading-relaxed">{e.text}</p>
                  </div>
                ))}
              </div>
            </section>
          )}
        </div>

        {/* Right rail */}
        <aside className="w-full xl:w-80 shrink-0 xl:sticky xl:top-24 space-y-6">
          {/* Completion */}
          <div className="bg-[#0F766E] text-white rounded-2xl p-6 shadow-xl shadow-teal-900/10 relative overflow-hidden">
            <div className="absolute -right-6 -top-6 w-24 h-24 bg-white/10 rounded-full blur-2xl" />
            <h3 className="text-[10px] font-bold text-white/70 uppercase tracking-widest mb-2">Completion Status</h3>
            <div className="flex items-end space-x-3 mb-4">
              <span className="text-4xl font-bold font-poppins">{spec.completionScore}%</span>
              <span className="text-sm text-teal-100 font-medium mb-1">
                {spec.validationErrors.length === 0 ? 'Checks passed' : 'Needs attention'}
              </span>
            </div>
            <div className="h-2 w-full bg-white/20 rounded-full overflow-hidden">
              <div className="h-full bg-white rounded-full transition-all" style={{ width: `${spec.completionScore}%` }} />
            </div>
          </div>

          {/* Suggestions */}
          <div className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden">
            <div className="p-4 bg-teal-50/50 flex items-center gap-2">
              <Sparkles size={16} className="text-teal-500" />
              <span className="text-sm font-bold text-teal-800">AI Suggestions ({pendingSuggestions.length})</span>
            </div>
            <div className="p-4 space-y-4 border-t border-slate-100">
              {spec.suggestions.length === 0 && <p className="text-xs text-slate-400">No suggestions.</p>}
              {spec.suggestions.map((s) => (
                <div key={s.id} className="bg-white border border-teal-100 rounded-xl p-4 shadow-sm relative overflow-hidden">
                  <div className={cn('absolute top-0 left-0 w-1 h-full', s.applied ? 'bg-green-400' : 'bg-teal-400')} />
                  <h4 className="text-sm font-bold text-slate-800 mb-1">{s.title}</h4>
                  <p className="text-xs text-slate-500 mb-3 leading-relaxed">{s.description}</p>
                  {s.effect ? (
                    <button
                      onClick={() => applySuggestion.mutate({ suggestionId: s.id, applied: !s.applied })}
                      disabled={applySuggestion.isPending}
                      aria-label={`${s.applied ? 'Undo' : 'Apply'} suggestion: ${s.title}`}
                      className={cn(
                        'text-xs font-bold flex items-center gap-1 disabled:opacity-50',
                        s.applied ? 'text-slate-500 hover:text-slate-700' : 'text-teal-600 hover:text-teal-800'
                      )}
                    >
                      {s.applied ? <><Undo2 size={14} /> Added — Undo</> : <><PlusCircle size={14} /> Add to Spec</>}
                    </button>
                  ) : (
                    // No machine-applicable effect — say so rather than offering a button that does nothing.
                    <span className="text-[10px] font-bold text-slate-400 bg-slate-50 px-2 py-1 rounded uppercase tracking-wide">
                      Advice only
                    </span>
                  )}
                </div>
              ))}
            </div>
          </div>

          {/* Risks */}
          {spec.risks.length > 0 && (
            <div className="bg-white rounded-2xl border border-amber-200 shadow-sm overflow-hidden">
              <div className="p-4 bg-amber-50 flex items-center gap-2">
                <AlertTriangle size={16} className="text-amber-600" />
                <span className="text-sm font-bold text-amber-800">Review Needed ({openRisks.length})</span>
              </div>
              <div className="p-4 space-y-3 border-t border-amber-100">
                {spec.risks.map((r) => (
                  <div
                    key={r.id}
                    className={cn(
                      'rounded-xl p-4 shadow-sm border',
                      r.resolved ? 'bg-slate-50 border-slate-200' : 'bg-white border-amber-200'
                    )}
                  >
                    <h4 className={cn('text-sm font-bold mb-1', r.resolved ? 'text-slate-500' : 'text-slate-800')}>
                      {r.title}
                    </h4>
                    <p className="text-xs text-slate-500 leading-relaxed mb-3">{r.description}</p>
                    <button
                      onClick={() => resolveRisk.mutate({ riskId: r.id, resolved: !r.resolved })}
                      disabled={resolveRisk.isPending}
                      aria-label={`${r.resolved ? 'Un-review' : 'Mark as reviewed'}: ${r.title}`}
                      className={cn(
                        'text-xs font-bold flex items-center gap-1 disabled:opacity-50',
                        r.resolved ? 'text-slate-500 hover:text-slate-700' : 'text-amber-700 hover:text-amber-900'
                      )}
                    >
                      {r.resolved
                        ? <><Undo2 size={14} /> Reviewed — undo</>
                        : <><ShieldCheck size={14} /> Mark as reviewed</>}
                    </button>
                  </div>
                ))}
              </div>
            </div>
          )}
        </aside>
      </main>

      {/* Sticky approval bar */}
      <div className="bg-white border-t border-slate-200 px-8 py-4 sticky bottom-0 z-40 shadow-[0_-10px_30px_rgba(0,0,0,0.05)]">
        <div className="max-w-[1600px] mx-auto flex items-center justify-between gap-4 flex-wrap">
          <ApprovalChecklist
            items={spec.checklist}
            disabled={confirmItem.isPending}
            onToggle={(key, confirmed) => confirmItem.mutate({ key, confirmed })}
          />
          <div className="flex flex-col items-end gap-1">
            <Button
              onClick={handleApprove}
              disabled={!canApprove || approve.isPending}
              isLoading={approve.isPending}
              className="h-12 px-8 rounded-xl bg-[#0F766E] hover:bg-[#0D6B63] text-white font-bold flex items-center gap-2 shadow-lg"
            >
              <span>Approve &amp; Set Up Alerts</span>
              <ArrowRight size={18} />
            </Button>
            {!canApprove && <p className="text-[11px] text-slate-500 max-w-xs text-right">{blockedReason}</p>}
          </div>
        </div>
      </div>
    </div>
  );
};

export default BlueprintReviewPage;
