import { IR } from '../../types';
import { lines, withTrailingNewline } from '../helpers';

const banner = (extra: string) =>
  lines(`/**`, ` * Auto-generated by FlowForge. Do not edit by hand.`, ` * ${extra}`, ` */`);

// ── client/src/App.tsx (route table from the IR) ───────────────────
export const renderAppTsx = (ir: IR): string => {
  const entityImports = ir.entities.flatMap((e) => [
    `import ${e.modelName}ListPage from './pages/${e.varName}/${e.modelName}ListPage';`,
    `import ${e.modelName}FormPage from './pages/${e.varName}/${e.modelName}FormPage';`,
    `import ${e.modelName}DetailPage from './pages/${e.varName}/${e.modelName}DetailPage';`,
  ]);

  const entityRoutes = ir.entities.flatMap((e) => [
    `          <Route path="/${e.routeBase}" element={<${e.modelName}ListPage />} />`,
    `          <Route path="/${e.routeBase}/new" element={<${e.modelName}FormPage />} />`,
    `          <Route path="/${e.routeBase}/:id" element={<${e.modelName}DetailPage />} />`,
    `          <Route path="/${e.routeBase}/:id/edit" element={<${e.modelName}FormPage />} />`,
  ]);

  return withTrailingNewline(
    lines(
      banner('Application routes.'),
      `import { Routes, Route, Navigate } from 'react-router-dom';`,
      `import ProtectedRoute from './auth/ProtectedRoute';`,
      `import Layout from './components/Layout';`,
      `import LoginPage from './auth/LoginPage';`,
      `import DashboardPage from './pages/DashboardPage';`,
      ...entityImports,
      ``,
      `export default function App() {`,
      `  return (`,
      `    <Routes>`,
      `      <Route path="/login" element={<LoginPage />} />`,
      `      <Route element={<ProtectedRoute />}>`,
      `        <Route element={<Layout />}>`,
      `          <Route path="/" element={<DashboardPage />} />`,
      ...entityRoutes,
      `        </Route>`,
      `      </Route>`,
      `      <Route path="*" element={<Navigate to="/" replace />} />`,
      `    </Routes>`,
      `  );`,
      `}`
    )
  );
};
