import { IR, EntityIR, FieldIR } from '../../types';
import { camel } from '../../naming';
import { lines, withTrailingNewline } from '../helpers';

const banner = (extra: string) =>
  lines(`/**`, ` * Auto-generated by FlowForge. Do not edit by hand.`, ` * ${extra}`, ` */`);

// Response-envelope collection key for an entity list (matches the backend controller).
const collectionKeyOf = (e: EntityIR): string => camel(e.tableName.replace(/_/g, ' '));

// The attribute used to label a row (mirrors preview.service displayFieldAttr).
const displayAttrOf = (e: EntityIR): string => {
  const text = e.fields.find((f) => f.fieldType === 'text' && !f.isStatus);
  if (text) return text.attrName;
  const nonRef = e.fields.find((f) => !f.isStatus && !f.ref);
  return nonRef?.attrName ?? e.fields.find((f) => !f.isStatus)?.attrName ?? 'id';
};

const fieldMeta = (f: FieldIR, ir: IR): Record<string, unknown> => {
  const m: Record<string, unknown> = {
    attrName: f.attrName,
    label: f.specName,
    fieldType: f.fieldType,
    required: f.required,
  };
  if (f.enumValues && f.enumValues.length) m.enumValues = f.enumValues;
  if (f.isStatus) m.isStatus = true;
  if (f.ref) {
    const target = ir.entityByKey[f.ref.targetKey];
    m.ref = {
      targetRouteBase: target?.routeBase ?? f.ref.targetKey,
      targetKey: f.ref.targetKey,
      targetLabel: target?.label ?? f.ref.targetModel,
      displayAttr: target ? displayAttrOf(target) : 'id',
    };
  }
  return m;
};

// ── client/src/lib/meta.ts (emitted entity/workflow metadata) ──────
export const renderMetaTs = (ir: IR): string => {
  const entities = ir.entities.map((e) => ({
    key: e.key,
    label: e.label,
    modelName: e.modelName,
    routeBase: e.routeBase,
    collectionKey: collectionKeyOf(e),
    singularKey: e.varName,
    displayAttr: displayAttrOf(e),
    isWorkflow: e.isWorkflow,
    fields: e.fields.map((f) => fieldMeta(f, ir)),
  }));

  const workflow = ir.workflow
    ? {
        entityKey: ir.workflow.entityKey,
        routeBase: ir.entityByKey[ir.workflow.entityKey]?.routeBase ?? '',
        statusAttr: ir.workflow.statusAttr,
        states: ir.workflow.states.map((s) => ({ key: s.key, label: s.label, isInitial: s.isInitial, isFinal: s.isFinal })),
        transitions: ir.workflow.transitions.map((t) => ({ from: t.from, to: t.to, label: t.label, roleKey: t.roleKey ?? null })),
      }
    : null;

  return withTrailingNewline(
    lines(
      banner('Entity + workflow metadata driving the generated screens.'),
      `export type FieldType =`,
      `  | 'text' | 'richtext' | 'number' | 'currency' | 'date' | 'time'`,
      `  | 'boolean' | 'enum' | 'phone' | 'email' | 'reference';`,
      ``,
      `export interface FieldRef {`,
      `  targetRouteBase: string;`,
      `  targetKey: string;`,
      `  targetLabel: string;`,
      `  displayAttr: string;`,
      `}`,
      ``,
      `export interface FieldMeta {`,
      `  attrName: string;`,
      `  label: string;`,
      `  fieldType: FieldType;`,
      `  required: boolean;`,
      `  enumValues?: string[];`,
      `  isStatus?: boolean;`,
      `  ref?: FieldRef;`,
      `}`,
      ``,
      `export interface EntityMeta {`,
      `  key: string;`,
      `  label: string;`,
      `  modelName: string;`,
      `  routeBase: string;`,
      `  collectionKey: string;`,
      `  singularKey: string;`,
      `  displayAttr: string;`,
      `  isWorkflow: boolean;`,
      `  fields: FieldMeta[];`,
      `}`,
      ``,
      `export interface WorkflowState { key: string; label: string; isInitial: boolean; isFinal: boolean; }`,
      `export interface WorkflowTransition { from: string; to: string; label: string; roleKey: string | null; }`,
      `export interface WorkflowMeta {`,
      `  entityKey: string;`,
      `  routeBase: string;`,
      `  statusAttr: string;`,
      `  states: WorkflowState[];`,
      `  transitions: WorkflowTransition[];`,
      `}`,
      ``,
      `export const ENTITIES: EntityMeta[] = ${JSON.stringify(entities, null, 2)};`,
      ``,
      `export const WORKFLOW: WorkflowMeta | null = ${JSON.stringify(workflow, null, 2)};`,
      ``,
      `export const getEntity = (routeBase: string): EntityMeta | undefined =>`,
      `  ENTITIES.find((e) => e.routeBase === routeBase);`
    )
  );
};

// ── client/src/lib/format.ts ───────────────────────────────────────
export const renderFormatTs = (): string =>
  withTrailingNewline(
    lines(
      banner('Value formatting for tables + detail views.'),
      `import type { FieldMeta } from './meta';`,
      ``,
      `export function formatValue(field: FieldMeta, value: unknown): string {`,
      `  if (value === null || value === undefined || value === '') return '\\u2014';`,
      `  if (field.fieldType === 'boolean') return value ? 'Yes' : 'No';`,
      `  if (field.fieldType === 'currency') return Number(value).toFixed(2);`,
      `  return String(value);`,
      `}`,
      ``,
      `export function recordLabel(displayAttr: string, row: Record<string, unknown>): string {`,
      `  const v = row[displayAttr];`,
      `  if (v === null || v === undefined || v === '') return '#' + String(row.id ?? '');`,
      `  return String(v);`,
      `}`
    )
  );

// ── client/src/components/StateBadge.tsx ───────────────────────────
export const renderStateBadgeTsx = (): string =>
  withTrailingNewline(
    lines(
      banner('Workflow status pill.'),
      `export default function StateBadge({ label }: { label: string }) {`,
      `  return <span className="badge">{label}</span>;`,
      `}`
    )
  );

// ── client/src/components/DataTable.tsx ────────────────────────────
export const renderDataTableTsx = (): string =>
  withTrailingNewline(
    lines(
      banner('Generic data table.'),
      `import type { ReactNode } from 'react';`,
      ``,
      `export interface Column { key: string; label: string; }`,
      ``,
      `interface Props {`,
      `  columns: Column[];`,
      `  rows: Record<string, any>[];`,
      `  renderCell: (row: Record<string, any>, col: Column) => ReactNode;`,
      `  actions?: (row: Record<string, any>) => ReactNode;`,
      `}`,
      ``,
      `export default function DataTable({ columns, rows, renderCell, actions }: Props) {`,
      `  return (`,
      `    <table className="table">`,
      `      <thead>`,
      `        <tr>`,
      `          {columns.map((c) => (`,
      `            <th key={c.key}>{c.label}</th>`,
      `          ))}`,
      `          {actions ? <th>Actions</th> : null}`,
      `        </tr>`,
      `      </thead>`,
      `      <tbody>`,
      `        {rows.map((row) => (`,
      `          <tr key={String(row.id)}>`,
      `            {columns.map((c) => (`,
      `              <td key={c.key}>{renderCell(row, c)}</td>`,
      `            ))}`,
      `            {actions ? <td>{actions(row)}</td> : null}`,
      `          </tr>`,
      `        ))}`,
      `      </tbody>`,
      `    </table>`,
      `  );`,
      `}`
    )
  );

// ── client/src/components/Layout.tsx ───────────────────────────────
export const renderLayoutTsx = (ir: IR): string =>
  withTrailingNewline(
    lines(
      banner('App shell: sidebar nav + top bar + routed content.'),
      `import { NavLink, Outlet, useNavigate } from 'react-router-dom';`,
      `import { getUser, clearSession } from '../auth/session';`,
      `import { ENTITIES } from '../lib/meta';`,
      ``,
      `export default function Layout() {`,
      `  const navigate = useNavigate();`,
      `  const user = getUser();`,
      `  const logout = () => {`,
      `    clearSession();`,
      `    navigate('/login');`,
      `  };`,
      `  return (`,
      `    <div className="app-shell">`,
      `      <aside className="sidebar">`,
      `        <div className="sidebar-brand">${ir.appName}</div>`,
      `        <nav className="sidebar-nav">`,
      `          <NavLink to="/" end className={({ isActive }) => 'nav-item' + (isActive ? ' active' : '')}>`,
      `            Dashboard`,
      `          </NavLink>`,
      `          {ENTITIES.map((e) => (`,
      `            <NavLink`,
      `              key={e.key}`,
      `              to={'/' + e.routeBase}`,
      `              className={({ isActive }) => 'nav-item' + (isActive ? ' active' : '')}`,
      `            >`,
      `              {e.label}`,
      `            </NavLink>`,
      `          ))}`,
      `        </nav>`,
      `      </aside>`,
      `      <div className="main-area">`,
      `        <header className="topbar">`,
      `          <div className="topbar-user">`,
      `            <span>{user ? user.fullName || user.email : 'User'}</span>`,
      `            {user ? <span className="role-chip">{user.role}</span> : null}`,
      `            <button className="btn btn-ghost btn-sm" onClick={logout}>Logout</button>`,
      `          </div>`,
      `        </header>`,
      `        <main className="content">`,
      `          <Outlet />`,
      `        </main>`,
      `      </div>`,
      `    </div>`,
      `  );`,
      `}`
    )
  );
