import { IR } from '../../types';
import { lines, withTrailingNewline } from '../helpers';

/**
 * Emitted React + Vite + TypeScript SPA scaffold (under `client/`). All code is
 * strict-TS clean and uses string concatenation (no runtime template literals)
 * so the emitter can interpolate build-time values freely and the output
 * type-checks in the compile test.
 */

const banner = (extra: string) =>
  lines(
    `/**`,
    ` * Auto-generated by FlowForge. Do not edit by hand.`,
    ` * ${extra}`,
    ` */`
  );

// ── client/package.json ────────────────────────────────────────────
export const renderClientPackageJson = (ir: IR): string => {
  const pkg = {
    name: `${ir.appName}-client`,
    private: true,
    version: '1.0.0',
    type: 'module',
    scripts: { dev: 'vite', build: 'tsc && vite build', preview: 'vite preview' },
    dependencies: {
      react: '^18.3.1',
      'react-dom': '^18.3.1',
      'react-router-dom': '^6.26.0',
    },
    devDependencies: {
      '@types/react': '^18.3.3',
      '@types/react-dom': '^18.3.0',
      '@vitejs/plugin-react': '^4.3.1',
      typescript: '^5.5.0',
      vite: '^5.4.0',
    },
  };
  return withTrailingNewline(JSON.stringify(pkg, null, 2));
};

// ── client/tsconfig.json ───────────────────────────────────────────
export const renderClientTsconfig = (): string => {
  const cfg = {
    compilerOptions: {
      target: 'ES2020',
      useDefineForClassFields: true,
      lib: ['ES2020', 'DOM', 'DOM.Iterable'],
      module: 'ESNext',
      skipLibCheck: true,
      moduleResolution: 'bundler',
      resolveJsonModule: true,
      isolatedModules: true,
      noEmit: true,
      jsx: 'react-jsx',
      strict: true,
      noUnusedLocals: false,
      forceConsistentCasingInFileNames: true,
    },
    include: ['src'],
  };
  return withTrailingNewline(JSON.stringify(cfg, null, 2));
};

// ── client/vite.config.ts ──────────────────────────────────────────
export const renderViteConfig = (): string =>
  withTrailingNewline(
    lines(
      `import { defineConfig } from 'vite';`,
      `import react from '@vitejs/plugin-react';`,
      ``,
      `export default defineConfig({`,
      `  plugins: [react()],`,
      `  server: { port: 5173 },`,
      `});`
    )
  );

// ── client/index.html ──────────────────────────────────────────────
export const renderIndexHtml = (ir: IR): string =>
  withTrailingNewline(
    lines(
      `<!doctype html>`,
      `<html lang="en">`,
      `  <head>`,
      `    <meta charset="UTF-8" />`,
      `    <meta name="viewport" content="width=device-width, initial-scale=1.0" />`,
      `    <title>${ir.appName}</title>`,
      `  </head>`,
      `  <body>`,
      `    <div id="root"></div>`,
      `    <script type="module" src="/src/main.tsx"></script>`,
      `  </body>`,
      `</html>`
    )
  );

// ── client/src/env.d.ts (so import.meta.env type-checks standalone) ─
export const renderEnvDts = (): string =>
  withTrailingNewline(
    lines(
      `interface ImportMetaEnv {`,
      `  readonly VITE_API_URL?: string;`,
      `}`,
      `interface ImportMeta {`,
      `  readonly env: ImportMetaEnv;`,
      `}`
    )
  );

// ── client/.env.example ────────────────────────────────────────────
export const renderClientEnvExample = (): string =>
  withTrailingNewline(lines(`VITE_API_URL=http://localhost:4000/api`));

// ── client/src/main.tsx ────────────────────────────────────────────
export const renderMainTsx = (): string =>
  withTrailingNewline(
    lines(
      banner('Application entry point.'),
      `import React from 'react';`,
      `import ReactDOM from 'react-dom/client';`,
      `import { BrowserRouter } from 'react-router-dom';`,
      `import App from './App';`,
      `import './theme.css';`,
      ``,
      `ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(`,
      `  <React.StrictMode>`,
      `    <BrowserRouter>`,
      `      <App />`,
      `    </BrowserRouter>`,
      `  </React.StrictMode>`,
      `);`
    )
  );

// ── client/src/theme.css (CSS variables from the ThemeConfig) ──────
export const renderThemeCss = (ir: IR): string => {
  const t = ir.theme;
  return withTrailingNewline(
    lines(
      `/* Auto-generated by FlowForge — brand theme (${ir.domain}). */`,
      `:root {`,
      `  --color-primary: ${t.colors.primary};`,
      `  --color-secondary: ${t.colors.secondary};`,
      `  --color-accent: ${t.colors.accent};`,
      `  --font-heading: '${t.fonts.heading}', system-ui, sans-serif;`,
      `  --font-body: '${t.fonts.body}', system-ui, sans-serif;`,
      `  --bg: #f8fafc;`,
      `  --surface: #ffffff;`,
      `  --border: #e2e8f0;`,
      `  --text: #0f172a;`,
      `  --muted: #64748b;`,
      `}`,
      ``,
      `* { box-sizing: border-box; }`,
      `body { margin: 0; font-family: var(--font-body); color: var(--text); background: var(--bg); }`,
      `h1, h2, h3 { font-family: var(--font-heading); margin: 0 0 0.5rem; }`,
      `a { color: var(--color-primary); text-decoration: none; }`,
      `.muted { color: var(--muted); }`,
      ``,
      `/* Layout */`,
      `.app-shell { display: flex; min-height: 100vh; }`,
      `.sidebar { width: 230px; background: var(--surface); border-right: 1px solid var(--border); padding: 1rem; }`,
      `.sidebar-brand { font-family: var(--font-heading); font-weight: 700; color: var(--color-primary); padding: 0.5rem; margin-bottom: 1rem; }`,
      `.sidebar-nav { display: flex; flex-direction: column; gap: 0.25rem; }`,
      `.nav-item { padding: 0.5rem 0.75rem; border-radius: 8px; color: var(--muted); font-weight: 500; }`,
      `.nav-item:hover { background: #f1f5f9; color: var(--text); }`,
      `.nav-item.active { background: color-mix(in srgb, var(--color-primary) 12%, transparent); color: var(--color-primary); }`,
      `.main-area { flex: 1; display: flex; flex-direction: column; }`,
      `.topbar { height: 56px; background: var(--surface); border-bottom: 1px solid var(--border); display: flex; align-items: center; justify-content: flex-end; padding: 0 1.5rem; }`,
      `.topbar-user { display: flex; align-items: center; gap: 0.75rem; font-size: 0.9rem; }`,
      `.role-chip { background: color-mix(in srgb, var(--color-secondary) 15%, transparent); color: var(--color-secondary); border-radius: 999px; padding: 2px 10px; font-size: 0.72rem; font-weight: 700; text-transform: capitalize; }`,
      `.content { padding: 2rem; }`,
      ``,
      `/* Components */`,
      `.card { background: var(--surface); border: 1px solid var(--border); border-radius: 14px; padding: 1.25rem; }`,
      `.btn { border: 0; border-radius: 8px; padding: 0.5rem 1rem; font-weight: 600; cursor: pointer; font-size: 0.9rem; }`,
      `.btn-primary { background: var(--color-primary); color: #fff; }`,
      `.btn-primary:disabled { opacity: 0.6; cursor: default; }`,
      `.btn-ghost { background: transparent; color: var(--muted); border: 1px solid var(--border); }`,
      `.btn-sm { padding: 0.3rem 0.6rem; font-size: 0.8rem; }`,
      `.badge { display: inline-block; background: color-mix(in srgb, var(--color-accent) 22%, transparent); color: var(--text); border-radius: 999px; padding: 2px 10px; font-size: 0.72rem; font-weight: 700; }`,
      `.field { display: flex; flex-direction: column; gap: 0.3rem; margin-bottom: 0.9rem; }`,
      `.field > span { font-size: 0.8rem; font-weight: 600; color: var(--muted); }`,
      `.input, .select, textarea.input { width: 100%; padding: 0.55rem 0.7rem; border: 1px solid var(--border); border-radius: 8px; font: inherit; background: #fff; }`,
      `.input:focus, .select:focus { outline: none; border-color: var(--color-primary); }`,
      `.table { width: 100%; border-collapse: collapse; background: var(--surface); border: 1px solid var(--border); border-radius: 14px; overflow: hidden; }`,
      `.table th { text-align: left; background: var(--color-primary); color: #fff; padding: 0.7rem 1rem; font-size: 0.82rem; }`,
      `.table td { padding: 0.7rem 1rem; border-top: 1px solid var(--border); font-size: 0.88rem; }`,
      `.table tr:hover td { background: #f8fafc; }`,
      `.row-between { display: flex; align-items: center; justify-content: space-between; margin-bottom: 1.25rem; gap: 1rem; }`,
      `.grid-2 { display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; }`,
      `.stat-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(180px, 1fr)); gap: 1rem; }`,
      `.stat-value { font-size: 2rem; font-weight: 700; font-family: var(--font-heading); }`,
      `.alert-error { background: #fef2f2; color: #b91c1c; border: 1px solid #fecaca; border-radius: 8px; padding: 0.6rem 0.8rem; margin-bottom: 0.8rem; font-size: 0.85rem; }`,
      `.auth-wrap { min-height: 100vh; display: flex; align-items: center; justify-content: center; background: var(--bg); }`,
      `.auth-card { width: 360px; }`,
      `.brand-title { color: var(--color-primary); }`,
      `.link-btn { background: none; border: 0; color: var(--color-primary); cursor: pointer; font: inherit; padding: 0; }`
    )
  );
};

// ── client/src/api/client.ts ───────────────────────────────────────
export const renderApiClient = (): string =>
  withTrailingNewline(
    lines(
      banner('Typed fetch client for the generated REST API.'),
      `import { getToken, clearSession } from '../auth/session';`,
      ``,
      `const BASE_URL = (import.meta.env.VITE_API_URL || 'http://localhost:4000/api').replace(/\\/$/, '');`,
      ``,
      `interface Envelope<T> {`,
      `  success: boolean;`,
      `  data?: T;`,
      `  message?: string;`,
      `}`,
      ``,
      `async function request<T>(method: string, path: string, body?: unknown): Promise<T> {`,
      `  const headers: Record<string, string> = { 'Content-Type': 'application/json' };`,
      `  const token = getToken();`,
      `  if (token) headers['Authorization'] = 'Bearer ' + token;`,
      `  const res = await fetch(BASE_URL + path, {`,
      `    method,`,
      `    headers,`,
      `    body: body !== undefined ? JSON.stringify(body) : undefined,`,
      `  });`,
      `  if (res.status === 401) clearSession();`,
      `  const json = (await res.json().catch(() => ({}))) as Envelope<T>;`,
      `  if (!res.ok || !json.success) {`,
      `    throw new Error(json.message || ('Request failed (' + res.status + ')'));`,
      `  }`,
      `  return json.data as T;`,
      `}`,
      ``,
      `export const api = {`,
      `  get: <T>(path: string) => request<T>('GET', path),`,
      `  post: <T>(path: string, body?: unknown) => request<T>('POST', path, body),`,
      `  put: <T>(path: string, body?: unknown) => request<T>('PUT', path, body),`,
      `  del: <T>(path: string) => request<T>('DELETE', path),`,
      `};`
    )
  );

// ── client/src/auth/session.ts ─────────────────────────────────────
export const renderSession = (): string =>
  withTrailingNewline(
    lines(
      banner('Auth session (token + user in localStorage).'),
      `export interface AuthUser {`,
      `  id: number;`,
      `  email: string;`,
      `  fullName?: string;`,
      `  role: string;`,
      `}`,
      ``,
      `const TOKEN_KEY = 'ff_token';`,
      `const USER_KEY = 'ff_user';`,
      ``,
      `export const getToken = (): string | null => localStorage.getItem(TOKEN_KEY);`,
      ``,
      `export const getUser = (): AuthUser | null => {`,
      `  const raw = localStorage.getItem(USER_KEY);`,
      `  if (!raw) return null;`,
      `  try {`,
      `    return JSON.parse(raw) as AuthUser;`,
      `  } catch {`,
      `    return null;`,
      `  }`,
      `};`,
      ``,
      `export const setSession = (token: string, user: AuthUser): void => {`,
      `  localStorage.setItem(TOKEN_KEY, token);`,
      `  localStorage.setItem(USER_KEY, JSON.stringify(user));`,
      `};`,
      ``,
      `export const clearSession = (): void => {`,
      `  localStorage.removeItem(TOKEN_KEY);`,
      `  localStorage.removeItem(USER_KEY);`,
      `};`,
      ``,
      `export const isAuthenticated = (): boolean => !!getToken();`
    )
  );

// ── client/Dockerfile (build Vite → nginx) ────────────────────────
export const renderClientDockerfile = (): string =>
  withTrailingNewline(
    lines(
      `# syntax=docker/dockerfile:1`,
      `FROM node:22-alpine AS build`,
      `WORKDIR /app`,
      `COPY package*.json ./`,
      `RUN npm ci`,
      `COPY . .`,
      `RUN npm run build`,
      ``,
      `FROM nginx:alpine`,
      `COPY nginx.conf /etc/nginx/conf.d/default.conf`,
      `COPY --from=build /app/dist /usr/share/nginx/html`,
      `EXPOSE 80`
    )
  );

export const renderClientNginxConf = (): string =>
  withTrailingNewline(
    lines(
      `server {`,
      `  listen 80;`,
      `  location / {`,
      `    root /usr/share/nginx/html;`,
      `    try_files $uri /index.html;`,
      `  }`,
      `}`
    )
  );

// ── client/src/auth/ProtectedRoute.tsx ─────────────────────────────
export const renderProtectedRoute = (): string =>
  withTrailingNewline(
    lines(
      banner('Redirects to /login when unauthenticated.'),
      `import { Navigate, Outlet } from 'react-router-dom';`,
      `import { isAuthenticated } from './session';`,
      ``,
      `export default function ProtectedRoute() {`,
      `  return isAuthenticated() ? <Outlet /> : <Navigate to="/login" replace />;`,
      `}`
    )
  );
