import { IR } from '../types';
import { lines, withTrailingNewline } from './helpers';

/**
 * Deploy-bundle renderers (Phase 5). Emitted by the Bundler stage so the
 * generated app ships deploy-ready: a Dockerfile, a Railway + Render config, a
 * LICENSE, and step-by-step self-host instructions. All deterministic (no clock
 * / random) so the golden snapshot stays stable.
 */

const dbName = (ir: IR) => `flowforge_${ir.domain}`;

// ── Dockerfile (multi-stage: build TS → slim runtime) ──────────────
export const renderDockerfile = (): string =>
  withTrailingNewline(
    lines(
      `# syntax=docker/dockerfile:1`,
      `# Build stage`,
      `FROM node:22-alpine AS build`,
      `WORKDIR /app`,
      `COPY package*.json ./`,
      `RUN npm ci`,
      `COPY . .`,
      `RUN npm run build`,
      ``,
      `# Runtime stage`,
      `FROM node:22-alpine`,
      `WORKDIR /app`,
      `ENV NODE_ENV=production`,
      `COPY package*.json ./`,
      `RUN npm ci --omit=dev`,
      `COPY --from=build /app/dist ./dist`,
      `EXPOSE 4000`,
      `CMD ["node", "dist/server.js"]`
    )
  );

export const renderDockerignore = (): string =>
  withTrailingNewline(lines(`node_modules`, `dist`, `.env`, `*.log`, `.git`));

// ── LICENSE (MIT; year omitted for deterministic output) ───────────
export const renderLicense = (ir: IR): string =>
  withTrailingNewline(
    lines(
      `MIT License`,
      ``,
      `Copyright (c) ${ir.appName}`,
      ``,
      `Permission is hereby granted, free of charge, to any person obtaining a copy`,
      `of this software and associated documentation files (the "Software"), to deal`,
      `in the Software without restriction, including without limitation the rights`,
      `to use, copy, modify, merge, publish, distribute, sublicense, and/or sell`,
      `copies of the Software, and to permit persons to whom the Software is`,
      `furnished to do so, subject to the following conditions:`,
      ``,
      `The above copyright notice and this permission notice shall be included in all`,
      `copies or substantial portions of the Software.`,
      ``,
      `THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR`,
      `IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,`,
      `FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE`,
      `AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER`,
      `LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,`,
      `OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE`,
      `SOFTWARE.`
    )
  );

// ── railway.json (Railway: build from Dockerfile) ──────────────────
export const renderRailwayJson = (): string => {
  const cfg = {
    $schema: 'https://railway.app/railway.schema.json',
    build: { builder: 'DOCKERFILE', dockerfilePath: 'Dockerfile' },
    deploy: { startCommand: 'node dist/server.js', restartPolicyType: 'ON_FAILURE', restartPolicyMaxRetries: 3 },
  };
  return withTrailingNewline(JSON.stringify(cfg, null, 2));
};

// ── render.yaml (Render blueprint: web service + managed Postgres) ──
export const renderRenderYaml = (ir: IR): string =>
  withTrailingNewline(
    lines(
      `services:`,
      `  - type: web`,
      `    name: ${ir.appName}`,
      `    runtime: docker`,
      `    dockerfilePath: ./Dockerfile`,
      `    envVars:`,
      `      - key: DATABASE_URL`,
      `        fromDatabase:`,
      `          name: ${ir.appName}-db`,
      `          property: connectionString`,
      `      - key: JWT_SECRET`,
      `        generateValue: true`,
      `      - key: PORT`,
      `        value: 4000`,
      `databases:`,
      `  - name: ${ir.appName}-db`,
      `    databaseName: ${dbName(ir)}`,
      `    plan: free`
    )
  );

// ── DEPLOY.md (self-host instructions) ─────────────────────────────
export const renderDeployMd = (ir: IR): string => {
  const body = lines(
    `# Deploying ${ir.appName}`,
    ``,
    `This is a full-stack app generated by FlowForge — a Node/Express + PostgreSQL API (project root) and a React + Vite frontend (\`client/\`). Pick any option below.`,
    ``,
    `## Required environment variables`,
    ``,
    '| Variable | Required | Notes |',
    '|---|---|---|',
    '| `DATABASE_URL` | yes | PostgreSQL connection string |',
    '| `JWT_SECRET` | yes | long random string for signing tokens |',
    '| `JWT_EXPIRES` | no | token lifetime (default `30m`) |',
    '| `PORT` | no | HTTP port (default `4000`) |',
    ``,
    `## Option 1 — Local (Docker Compose)`,
    ``,
    '```bash',
    `docker compose up -d db      # start PostgreSQL`,
    `npm install`,
    `npm run migrate              # create the schema`,
    `npm run dev                  # or: docker compose up app`,
    '```',
    ``,
    `## Option 2 — Railway`,
    ``,
    `1. Push this project to a Git repo and create a new Railway project from it (\`railway.json\` builds the \`Dockerfile\`).`,
    `2. Add a PostgreSQL plugin; Railway injects \`DATABASE_URL\`.`,
    `3. Set \`JWT_SECRET\`. Run \`npm run migrate\` once (Railway shell) to create the schema.`,
    ``,
    `## Option 3 — Render`,
    ``,
    `1. Commit this project to Git and click **New > Blueprint**; Render reads \`render.yaml\` (web service + free Postgres). \`render.yaml\` covers the API; add a Static Site for \`client/\` (build \`npm run build\`, publish \`dist\`).`,
    `2. On first deploy, open a shell and run \`npm run migrate\`.`,
    ``,
    `## Frontend (client/)`,
    ``,
    `The React app lives in \`client/\`. It reads the API base URL from \`VITE_API_URL\` (default \`http://localhost:4000/api\`).`,
    ``,
    '```bash',
    `cd client`,
    `npm install`,
    `npm run dev            # http://localhost:5173`,
    `# or: npm run build    # static bundle in client/dist (served by client/Dockerfile via nginx)`,
    '```',
    ``,
    `\`docker compose up\` builds and serves all three: db, the API (:4000), and the client (:5173).`,
    ``,
    `> Generated apps store money values as \`NUMERIC\`; the \`pg\` driver returns them as strings to preserve precision.`
  );
  return withTrailingNewline(body);
};
