/** Tiny deterministic string-template helpers shared by all emitters. */

/** Join parts with newlines, dropping null/undefined/empty-string entries. */
export const lines = (...parts: Array<string | null | undefined | false>): string =>
  parts.filter((p): p is string => typeof p === 'string' && p.length > 0).join('\n');

/** Indent every non-empty line of a block by `n` two-space levels. */
export const indent = (block: string, n = 1): string => {
  const pad = '  '.repeat(n);
  return block
    .split('\n')
    .map((l) => (l.length ? pad + l : l))
    .join('\n');
};

/** A standard "generated file" banner comment. */
export const banner = (extra?: string): string =>
  lines(
    '/**',
    ' * Auto-generated by FlowForge. Do not edit by hand — regenerate from the',
    ' * approved WorkflowSpec instead.',
    extra ? ` * ${extra}` : undefined,
    ' */'
  );

/** Ensure a file ends with exactly one trailing newline. */
export const withTrailingNewline = (s: string): string => s.replace(/\n*$/, '\n');

/** JS string literal (single-quoted, escaped). */
export const q = (s: string): string => `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
