import { EntityIR, FieldIR, IR } from '../types';
import { sqlEnumList } from '../typeMap';
import { columnModel, indexesFor } from './ddl';
import { lines, withTrailingNewline } from './helpers';
import { renderNotificationsSchemaTable } from './notifications';

/** One column definition line inside a CREATE TABLE — derived from the shared model. */
const columnDef = (f: FieldIR): string => {
  const c = columnModel(f);
  const parts = [`"${c.name}" ${c.sqlType}`];
  if (c.notNull) parts.push('NOT NULL');
  if (c.defaultValue !== undefined) parts.push(`DEFAULT ${c.defaultValue}`);
  if (c.unique) parts.push('UNIQUE');
  if (c.ref) {
    parts.push(
      `REFERENCES "${c.ref.targetTable}" ("id") ON UPDATE ${c.ref.onUpdate} ON DELETE ${c.ref.onDelete}`
    );
  }
  if (c.check) parts.push(`CHECK (${c.check})`);
  return '  ' + parts.join(' ') + ',';
};

/** CREATE INDEX statements for an entity's foreign keys / declared-unique columns. */
const indexStatements = (e: EntityIR): string =>
  indexesFor(e)
    .map(
      (i) =>
        `CREATE${i.unique ? ' UNIQUE' : ''} INDEX "${i.name}" ON "${i.table}" ("${i.column}");`
    )
    .join('\n');

const auditColumns = lines(
  `  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),`,
  `  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()`
);

const createTable = (e: EntityIR): string =>
  lines(
    `CREATE TABLE "${e.tableName}" (`,
    `  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,`,
    e.fields.map(columnDef).join('\n'),
    auditColumns,
    `);`,
    indexStatements(e)
  );

const usersTable = (ir: IR): string =>
  lines(
    `CREATE TABLE "users" (`,
    `  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,`,
    `  "email" VARCHAR(255) NOT NULL UNIQUE,`,
    `  "password" VARCHAR(255) NOT NULL,`,
    `  "full_name" VARCHAR(255),`,
    `  "role" VARCHAR(64) NOT NULL CHECK ("role" IN (${sqlEnumList(ir.roleKeys)})),`,
    auditColumns,
    `);`
  );

/** Render `schema.sql` — all tables in dependency order (users first). */
export const renderSchema = (ir: IR): string => {
  const body = lines(
    `-- FlowForge generated PostgreSQL schema (${ir.domain}).`,
    `-- Tables are declared in dependency order so foreign keys always resolve.`,
    ``,
    usersTable(ir),
    ``,
    ir.entities.map((e) => createTable(e)).join('\n\n'),
    ``,
    renderNotificationsSchemaTable()
  );
  return withTrailingNewline(body);
};
